name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches: [ master ]
  workflow_dispatch:

jobs:
  CheckContent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Check HTML
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: .
          css: true
  BuildContainer:
    runs-on: ubuntu-latest
    needs: CheckContent
    if: github.ref == 'refs/heads/master'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to the container repository
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ghcr.io/grillbot/grillbot-navigation:master
  DeployToProduction:
    runs-on: ubuntu-latest
    environment: 'Production'
    needs: BuildContainer
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Execute deployment on SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_Username }}
          password: ${{ secrets.SSH_Password }}
          port: 22
          script:
            echo '${{ secrets.SSH_Password }}' | sudo -S /scripts/podman-reload.py grillbot-navigation
